# Generated by Django 4.1.3 on 2022-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MINIO', '0002_mydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydocument',
            name='doc',
            field=models.FileField(upload_to=''),
        ),
    ]
